project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/*.qmd"
  resources:
    - images

website:
  title: ""
  site-url: https://infinitelimit.ai
  page-footer:
    center: |
      © 2026 Brian Taylor ·  
      <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>  

  navbar:
    left:
      - href: about.qmd
        text: About
      - href: /
        text: Writing
    logo: images/logo-navbar.svg
    logo-alt: "Infinite Limit"
    logo-href: /

    right:
      - href: contact.qmd
        text: Contact

execute:
  enabled: true

format:
  html:
#    include-before-body:
#      - includes/subnav.html
    css: styles.css
    theme:
      light: default
      dark: darkly
    mainfont: Inter
    monofont: JetBrains Mono
    fontsize: 1.05em
    linestretch: 1.6
    toc: true
    code-copy: true
    smooth-scroll: true
    html-math-method: mathjax


